[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.124.1'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[params.utterances]
repo = "github_username/repo_name" # Repository to store comments
issueTerm = "pathname"
