name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Ensure this is your main content branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Hugo (Extended)
      run: |
        curl -Ls https://github.com/gohugoio/hugo/releases/download/v0.125.4/hugo_extended_0.125.4_Linux-64bit.tar.gz | tar -xz -C /tmp/
        sudo mv /tmp/hugo /usr/local/bin/hugo
        hugo version

    - name: Build
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.private_key }}
        publish_dir: ./public
