name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Ensure this is your main content branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc
        run: |
          wget -qO- "https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb" | sudo dpkg -i -

      
      - name: Install Hugo and R packages
        run: |
          Rscript -e 'install.packages("blogdown")'
          Rscript -e 'blogdown::install_hugo(version = "0.125.4", extended = TRUE)'

      - name: Render R Markdown and Build the Site
        run: |
          Rscript -e 'blogdown::build_site(build_rmd = "html")'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # This branch will be used to deploy
